import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Toaster } from "sonner";
import Providers from "@/providers/SessionProvider";
import QueryProvider from "@/providers/QueryProvider";
import { ModalProvider } from "@/providers/ModalProvider";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "CareerLab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        style={{ backgroundColor: '#F6F7F9' }}
      >
        <QueryProvider>
          <Providers>
            <ModalProvider>
              {children}
            </ModalProvider>
          </Providers>
        </QueryProvider>
        <Toaster position="top-right" />
        <SpeedInsights />
      </body>
    </html>
  );
}
